Transaction Initiation
Pending confirmations 
Est. time to conf.: in about 23 hours
Queue: 12,999 of 89,174
Time
24 minutes ago
12 Oct 2024 04:01:47 UTC
Amount transferred
0.04649819 BTC  · 2,902 USD
Size
3,900
Coindays destroyed
0
Weight
15,600
Virtual size
3,900 vB
Coinbase transaction
No
Witness data
No
RBF enabled
Yes
Lock time
865,275
Version
2
Main (29)
Input 0
1FZJJ5QGnnbHQQgp5yS7J5tMRGYiZF8oey 
Amount
 0.0014025 BTC  · 84.50 USD
Input 1
1CHFx6RZdKcpt4RaeLcTd7V6wjcMhDXRQy 
Amount
 0.00065164 BTC  · 39.26 USD
Input 2
1FZ9NMsMmqLt84WQodet7fr8Jb2R6H6bWU 
Amount
 0.00080966 BTC  · 48.78 USD
Input 3
1CHFx6RZdKcpt4RaeLcTd7V6wjcMhDXRQy 
Amount
 0.00033551 BTC  · 20.21 USD
Input 4
1JbirqL2h9uZGkX8SYWjjfVmQSidcwxv2J 
Amount
 0.0021725 BTC  · 135.60 USD
Input 5
1NWHnVxuUajiMEKoikaHLhnSvtcNTFWDdY 
Amount
 0.00075763 BTC  · 45.88 USD
Input 6
145VVmWDVCayo5BQ95zryRdKFMejer3bcv 
Amount
 0.00097314 BTC  · 58.63 USD
Input 7
bc1qn56zm7hsxzdshuxdc7s7ytcv3qznf7wntj80g3bQoLyYHUcAY 
Amount
 0.0056618 BTC  · 341.12 USD
Input 8
1YasXR9sKvV5j1YYeD6AJkTVBARmfTna2 
Amount
 0.00153587 BTC  · 92.53 USD
Input 9
Amount
 0.00110124 BTC  · 68.73 USD
Output 0
Change
1NgGL7ceDzzTnMp6j5jdLdfnowAzJwRAdh 
Amount
0.00059455 BTC  · 37.11 USD
Output 1
18F5iEKPKzWviKQncMUkb3HKhGVUb9K9SD 
Amount
0.04531474 BTC